In [239]:
import numpy as np
import random
from matplotlib import pyplot as plt
from tkinter import *
from tkinter import ttk

In [240]:
# idée pour la gestion des temps d'infection /vaccin , création d'un deuxieme vecteur 2d comportant les durées de vie des états actuels

In [241]:
# paramètres
#taille monde:
n = 5
m = 5
#taux d'infection :
rzero = 2

In [242]:
#génère un monde de taille n,m

def generate_spatial_world(n,m):
    return np.random.choice([0,None],size=(n,m),p = [0.9,0.1])

In [243]:
#génère la premiere infection aléatoire d'un monde de taille n,m

def infection_world(world):
    while True:
        n = random.randint(0,len(world[:,0])-1)
        m = random.randint(0,len(world[0,:])-1)
        if world[n,m] == 0:
            world[n,m] = 1
            break
    return world

In [244]:
#infecte la cellule x,y, si elle n'est pas vaccinée

def infection_cellule(world,x,y):
    worldc = world
    if world[x,y] != 2:
        worldc[x,y] = 1
    return worldc

In [245]:
#génère un tableau en 1d du voisinage de la case nm

def voisins(world,n,m):
    voisins=[]
    for i in range(0,len(world[0,:])):
        for j in range(0,len(world[:,0])):
            if max(abs(i-n),abs(j-m))<=1 and not(i==n and j == m) :
                voisins.append(world[i,j])
    return voisins

In [246]:
#vérifie si il y autre chose que des malades et cases vides dans le voisinage

def verif_voisins(world,n,m):
    for i in voisins(world,n,m):
        if i != None and i!= 1:
            return True
    return False

In [247]:
#fais évoluer le monde en effectuant un tour( pour le moment seul les nouvels infections sont gérées)

def tour(world,rzero):
    worldbis = world
    for i in range (0,len(world[:,0])-1):
        for j in range ( 0, len(world[0,:])-1):
            if world[i,j] == 1 and verif_voisins(worldbis,i,j):
                nb = 0 
                while nb < rzero and verif_voisins(worldbis,i,j):
                    x = i + (random.randint(-1,1))
                    y = j + (random.randint(-1,1))
                    if (x >= 0 and x <= len(world[:,0])-1) and (y>= 0 and y<= len(world[0,:])-1):
                        if worldbis[x,y] != None and worldbis[x,y]!= 1:
                            worldbis = infection_cellule(worldbis,x,y)
                            nb += 1
    return worldbis

In [248]:
#effectue le deplacement d'un membre du monde choisi de manière aléatoire

def deplacement(world):
    worldbis = world
    x1 = random.randint(0,len(world[:,0])-1)
    y1 = random.randint(0,len(world[0,:])-1)
    x2 = random.randint(0,len(world[:,0])-1)
    y2 = random.randint(0,len(world[0,:])-1)  
    while world[x1,y1] == None or (x1 == x2 and y1 == y2):
        x1 = random.randint(0,len(world[:,0])-1)
        y1 = random.randint(0,len(world[0,:])-1) 
    worldbis[x2,y2] = world[x1,y1]
    worldbis[x1,y1] = world[x2,y2]
    return world

In [249]:
#effectue x tour d'évolution du monde en ajoutant un déplacement aléatoire tous les freq_depla tours 

def tour_boucle(world,rzero,nbtour,freq_depla):
    i = 0
    while i < nbtour:
        if i%freq_depla == 0:
            world = deplacement(world)
        world = tour(world,rzero)
        i+= 1
    return world

tour_boucle(world,rzero,5,2)

array([[1, 1, 1, None, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, None, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=object)

In [251]:
def cycle_entier(n,m,nbtour,freq_depla,rzero):
    world = generate_spatial_world(n,m)
    world = infection_world(world)
    worldeux = world
    world = tour_boucle(world,rzero,nbtour,freq_depla)
    worldeux = tour_boucle(worldeux,rzero,nbtour,freq_depla)
    return world , worldeux
    
cycle_entier(n,m,10,5,2)

(array([[1, None, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, None, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=object),
 array([[1, None, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, None, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=object))

In [252]:
#essaie tkinter
def fenetre(x):
    fenetre = Tk()
    fenetre.geometry('400x400')
    fenetre.title('Sars-CoV2')
    fenetre.resizable(height = True, width = True)
    fenetre['bg'] = 'black'
    fenetre.mainloop()

fenetre(1)