In [3]:
import numpy as np
import random

from matplotlib import pyplot as plt


In [37]:
# paramètres
#taille monde:
n = 5
m = 5
#taux d'infection :
rzero = 2

In [58]:
def generate_spatial_world(n,m):
    return np.random.choice([0,None],size=(n,m),p = [0.9,0.1])
world = generate_spatial_world(n,m)
worldbis = generate_spatial_world(n,m)
print(world)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 None 0]
 [0 0 0 0 0]
 [0 None 0 0 0]]


In [57]:
def infection_world(world):
    while True:
        n = random.randint(0,len(world[:,0])-1)
        m = random.randint(0,len(world[0,:])-1)
        if world[n,m] == 0:
            world[n,m] = 1
            break
    return world
infection_world(world)

array([[0, 0, 0, 0, 0],
       [None, 0, 0, 0, 0],
       [0, None, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=object)